### ISSUE TITLE
bug: addon breaks default behavior for statistics

### ISSUE THREAD

**Issue by ruilya** [DerDemystifier/SwiftAnki_Quick-Anki-Navigation#1]
background: I have single parent deck for everything. Others are nested under.

Behavior w/o the addon:

1. Start anki application.
2. Press 't' on keyboard.
3. Get a view stats of the parent deck.

![изображение](https://github.com/DerDemystifier/SwiftAnki_Quick-Anki-Navigation/assets/1244545/e7d36b5b-9f81-4229-a8a3-1b9045d53848)

Behavior with the addon:

1. Start anki application.
2. Press 't' on keyboard.
3. Get a view of 'default' deck that has no statistics.

![изображение](https://github.com/DerDemystifier/SwiftAnki_Quick-Anki-Navigation/assets/1244545/3691c759-7393-4007-a424-cb3c8f703306)

**Comment by DerDemystifier** [comment]
Thank you for reporting the issue! I've updated the addon, please check for updates in Anki and verify if the issue is still present.

**Comment by ruilya** [comment]
Thank you! The issue is gone
