### ISSUE TITLE
Problem with Review Heatmap add-on

### ISSUE THREAD

**Issue by ngoclong19** [DerDemystifier/SwiftAnki_Quick-Anki-Navigation#2]
Steps to reproduce:

1. Install the Review Heatmap add-on from https://ankiweb.net/shared/info/1771074083
2. Start Anki
3. Click the Options button on the top of the heatmap (see attached image)
  ![the location of the heatmap Options button](https://github.com/user-attachments/assets/9d427357-36c2-4336-93fd-be2553d6bd5b)
4. Anki encounters a problem.

If I repeat step 3 again, the Review Heatmap Settings dialog will open.
This problem doesn't happen if I open the dialog via menu Tools -> Review Heatmap Options.

Below is the debug info from step 3:

```text
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 689, in _onBridgeCmd
  File "_aqt.hooks", line 5416, in __call__
  File "C:\Users\long\AppData\Roaming\Anki2\addons21\1467361433\__init__.py", line 76, in on_webview_did_receive_js_message
    currentDeck = int(message.split(":")[1])
IndexError: list index out of range

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Review Heatmap ['1771074083', 2022-06-30T08:43, 'None', '']
SwiftAnki Quick Anki Navigation with Keyboard Shortcuts ['1467361433', 2023-12-28T22:24, 'None', '']

===IDs of active AnkiWeb add-ons===
1467361433 1771074083

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Flexible Grading ['1715096333', 2024-06-09T00:08, 'None', mod]
AnkiWebView Inspector ['31746032', 2023-06-28T02:26, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-16T01:55, 'None', '']
```

**Comment by DerDemystifier** [comment]
Thank you for taking the time to report this. "Review Heatmap" is a popular addon so I will make sure to fix this.
The issue must be somewhere in the message that "Review Heatmap" sends upon click options. I need to better handle my messages from messages from other addons.

I will issue a fix shortly and update the addon. Please stay tuned.

**Comment by DerDemystifier** [comment]
I've updated the addon on AnkiWeb. Please update your addon and check if the problem is resolved on your end 😉

**Comment by ngoclong19** [comment]
Thank you for the fix! I can see that this has now been fixed and is working as expected.
